### ISSUE TITLE
Compilation on armv7-androideabi

### ISSUE THREAD

**Issue by asyade** [mozilla/lmdb-rs#37]
When you compile rkv for 'armv7-androideabi' target the compilation will faile cause the buid.rs script of lmdb-sys is not able to reconize which android api level is used (and then the ndk linker will fail), for my case to fix it i've added "-D__ANDROID_API__=21" to the build.rs (as a flags of CC), but i think isnt a realy suitable solution, any suggestion ?

**Comment by mykmelez** [comment]
Sorry for the delay responding!

You should be able to add `-D__ANDROID_API__=21` to the compiler flags without modifying build.rs using the cc crate's support for [external configuration via environment variables](https://github.com/alexcrichton/cc-rs#external-configuration-via-environment-variables).

However, ideally the build script would do that automatically. A search of `__ANDROID_API__` in Rust code on GitHub finds these two snippets in build.rs files:

* https://github.com/susytech/ring/blob/0ccbdcbfa04b8bed51d1f22cb17d2f415a86b7e7/build.rs#L591-L602
* https://github.com/cfcosta/poller/blob/c645dc3ffc65237afd41c723aee27ff445b02f12/vendor/ring/build.rs#L591-L596

It seems like we should be able to do something like the latter to hardcode a value for this define. But does `__ANDROID_API__` need to match the configuration of the crate that is using this crate, and if so, can we figure out what value it should have based on some environment variable?

**Comment by asyade** [comment]
Yes and no, the API version must match between crate libraries (I think it could work with different version but it's not recommended) and to my knowledge there is no environment variable to define which API version to use. But with the new NDK version (> 20 probably 19) you dont need to specify API version as an argument. API version is now attached to the linker binary you're using, for example to use API 29 set the linker entry of you're cargo config to `toolchains/llvm/prebuilt/[...]/aarch64-linux-android29-clang`.  I think it is no longer necessary to modify build.rs, it must be done by the root crate using cargo config.
