### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/lmdb-rs#38]
For the newly added `set_map_size()` and `info()`.

Thanks!

**Comment by mykmelez** [comment]
Version string update in progress over in #39.

**Comment by mykmelez** [comment]
After a delay caused by a Travis CI issue, builds passed, I merged the version update, and I built and published the new version:

https://crates.io/crates/lmdb-rkv/0.11.3

And I tagged it:

https://github.com/mozilla/lmdb-rs/tree/0.11.3

**Comment by ncloudioj** [comment]
Excellent! Thanks!
