### ISSUE TITLE
Include lmdb tests when running `cargo test`

### ISSUE THREAD

**Issue by victorporof** [mozilla/lmdb-rs#57]
We could run the actual lmdb tests themselves as well alongside the Rust tests. This might help spot potential crashes when running these tests under Mozilla's CI.

@mykmelez @ncloudioj thoughts?

**Comment by victorporof** [comment]
We have some crate tests that run under `./mach rusttests`

**Comment by victorporof** [comment]
This would be useful in conjunction with https://github.com/mozilla/rkv/pull/150

**Comment by ncloudioj** [comment]
@victorporof Including tests into the CI cycle always sounds good to me!

To be clear, are you referring those tests from the LMDB library, i.e. mtest1/2/../5.c, or something else?

**Comment by victorporof** [comment]
Yes, the tests in the LMDB library, i.e. what runs on `make test`.
