### ISSUE TITLE
Soundness bug using Cursor::iter_from()

### ISSUE THREAD

**Issue by panicfarm** [mozilla/lmdb-rs#79]
I ran into a soundness bug by letting an iterator outlive the underlying cursor.  In my safe code, I created an iterator using `Cursor::iter_from`. When `Cursor::iter_from` returned, the `ffi::MDB_cursor` got deallocated (during `unsafe RoCursor::drop`) but the pointer to it was retained inside the iterator that was returned in `Cursor::iter_from` while my safe code was iterating. That caused the soundness bug when after several successful iterations an unrelated part of the program wrote at that address.

Links to the code:
https://github.com/mozilla/lmdb-rs/blob/4363ec04260b8f1c7db6b1f5c0e1c59fd009c228/src/cursor.rs#L78

https://github.com/mozilla/lmdb-rs/blob/4363ec04260b8f1c7db6b1f5c0e1c59fd009c228/src/cursor.rs#L33 

https://github.com/mozilla/lmdb-rs/blob/4363ec04260b8f1c7db6b1f5c0e1c59fd009c228/src/cursor.rs#L148

I would add `unsafe` to `Cursor::iter_from` but I understand that this could cause a lot of changes to the API, so another idea may be better.

**Comment by rory** [comment]
I think I am getting this error too, and that it's related to https://github.com/mozilla/lmdb-rs/issues/25 & https://github.com/mozilla/lmdb-rs/pull/5

**Comment by garbageslam** [comment]
I also encountered this problem I think about a year ago in danburkert/lmdb-rs, when trying to return a rust iterator type wrapping the lmdb one, from a database abstraction layer object. It segfaulted a lot and I was never able to debug it, and eventually gave up and backed out of that idea. Thank you for explaining :)
